export default {
  legitarsasagok: [
    {
      nev: "Endeavor Air Inc.",
      osszes: 281625,
      latogatott: 127,
      torolt: 1,
      atlagos: 79,
      legforgalmassabb: "ATL",
      logo: "/images/tarsasagok/endeavor-air-inc.png",
      url: "endeavor-air-inc",
    },
    {
      nev: "American Airlines Inc.",
      osszes: 1018437,
      latogatott: 117,
      torolt: 2,
      atlagos: 68,
      legforgalmassabb: "DFW",
      logo: "/images/tarsasagok/american-airlines-inc.png",
      url: "american-airlines-inc",
    },
    {
      nev: "Alaska Airlines Inc.",
      osszes: 284697,
      latogatott: 77,
      torolt: 1,
      atlagos: 51,
      legforgalmassabb: "SEA",
      logo: "/images/tarsasagok/alaska-airlines-inc.png",
      url: "alaska-airlines-inc",
    },
    {
      nev: "JetBlue Airways",
      osszes: 321204,
      latogatott: 70,
      torolt: 1,
      atlagos: 79,
      legforgalmassabb: "BOS",
      logo: "/images/tarsasagok/jetblue-airways.png",
      url: "jetblue-airways",
    },
    {
      nev: "Delta Air Lines Inc.",
      osszes: 1073663,
      latogatott: 154,
      torolt: 0,
      atlagos: 68,
      legforgalmassabb: "ATL",
      logo: "/images/tarsasagok/delta-air-lines-inc.png",
      url: "delta-air-lines-inc",
    },
    {
      nev: "ExpressJet Airlines Inc.",
      osszes: 24389,
      latogatott: 111,
      torolt: 4,
      atlagos: 80,
      legforgalmassabb: "IAH",
      logo: "/images/tarsasagok/expressjet-airlines-inc.png",
      url: "expressjet-airlines-inc",
    },
    {
      nev: "Frontier Airlines Inc.",
      osszes: 149912,
      latogatott: 106,
      torolt: 2,
      atlagos: 68,
      legforgalmassabb: "BOS",
      logo: "/images/tarsasagok/frontier-airlines-inc.png",
      url: "frontier-airlines-inc",
    },
    {
      nev: "Allegiant Air",
      osszes: 115030,
      latogatott: 126,
      torolt: 1,
      atlagos: 71,
      legforgalmassabb: "SFB",
      logo: "/images/tarsasagok/allegiant-air.png",
      url: "allegiant-air",
    },
    {
      nev: "Hawaiian Airlines Inc.",
      osszes: 90637,
      latogatott: 19,
      torolt: 0,
      atlagos: 40,
      legforgalmassabb: "HNL",
      logo: "/images/tarsasagok/hawaiian-airlines-inc.png",
      url: "hawaiian-airlines-inc",
    },
    {
      nev: "Envoy Air",
      osszes: 351701,
      latogatott: 169,
      torolt: 3,
      atlagos: 65,
      legforgalmassabb: "ORD",
      logo: "/images/tarsasagok/envoy-air.png",
      url: "envoy-air",
    },
    {
      nev: "Spirit Air Lines",
      osszes: 224464,
      latogatott: 52,
      torolt: 2,
      atlagos: 69,
      legforgalmassabb: "FLL",
      logo: "/images/tarsasagok/spirit-air-lines.png",
      url: "spirit-air-lines",
    },
    {
      nev: "PSA Airlines Inc.",
      osszes: 313346,
      latogatott: 104,
      torolt: 2,
      atlagos: 70,
      legforgalmassabb: "CLT",
      logo: "/images/tarsasagok/psa-airlines-inc.png",
      url: "psa-airlines-inc",
    },
    {
      nev: "SkyWest Airlines Inc.",
      osszes: 909735,
      latogatott: 277,
      torolt: 2,
      atlagos: 84,
      legforgalmassabb: "ORD",
      logo: "/images/tarsasagok/skywest-airlines-inc.png",
      url: "skywest-airlines-inc",
    },
    {
      nev: "United Air Lines Inc.",
      osszes: 673640,
      latogatott: 122,
      torolt: 1,
      atlagos: 75,
      legforgalmassabb: "ORD",
      logo: "/images/tarsasagok/united-air-lines-inc.png",
      url: "united-air-lines-inc",
    },
    {
      nev: "Southwest Airlines Co.",
      osszes: 1463985,
      latogatott: 90,
      torolt: 2,
      atlagos: 52,
      legforgalmassabb: "MDW",
      logo: "/images/tarsasagok/southwest-airlines-co.png",
      url: "southwest-airlines-co",
    },
    {
      nev: "Mesa Airlines Inc.",
      osszes: 244057,
      latogatott: 130,
      torolt: 3,
      atlagos: 81,
      legforgalmassabb: "DFW",
      logo: "/images/tarsasagok/mesa-airlines-inc.png",
      url: "mesa-airlines-inc",
    },
    {
      nev: "Republic Airline",
      osszes: 360077,
      latogatott: 120,
      torolt: 2,
      atlagos: 69,
      legforgalmassabb: "LGA",
      logo: "/images/tarsasagok/republic-airline.png",
      url: "republic-airline",
    },
    {
      nev: "ExpressJet Airlines LLC",
      osszes: 119067,
      latogatott: 120,
      torolt: 4,
      atlagos: 86,
      legforgalmassabb: "ORD",
      logo: "/images/tarsasagok/expressjet-airlines-llc.png",
      url: "expressjet-airlines-llc",
    },
  ],
};
